name: Data Validation

on:
  push:
    branches:
     - main 

jobs:
  validation-pipeline:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setting up Python
       uses: actions/setup-python@v2
       with: 
         python-version: 3.9

     - name: Libraries Installation
       run: pip install pandas datatime

     - name: Run the script
       runs: python app.py

     - name: Publish files to github repo
       runs: mikeal/publish-to-github-action@master  
       env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH_NAME: 'main'      